env: gfootball
env_args:
  map_name: 5_vs_5
  num_agents: 2
  representation: simple115
  rewards: scoring, reward_13
  time_limit: 150
learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 500000
test_greedy: true
test_interval: 10000
test_nepisode: 32
