env: gfootball
env_args:
<<<<<<< HEAD:doe_epymarl-main/src/config/envs/gfootball_GPT_decomposition0_subtask0.yaml
  map_name: scenario_layer0_decomposition0_subtask0
  num_agents: 3
  representation: simple115
  rewards: scoring, reward_layer0_decomposition0_subtask0_sample0
=======
  map_name: 5_vs_5
  num_agents: 5
  representation: simple115
  rewards: scoring, reward_0
>>>>>>> origin/HEAD:doe_epymarl-main/src/config/envs/gfootball_RAG_reward0.yaml
  time_limit: 150
learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 2050000
test_greedy: true
test_interval: 10000
test_nepisode: 32
