env: gfootball
env_args:
  map_name: 1_vs_1_easy
  num_agents: 1
  representation: simple115
  rewards: scoring, checkpoints
  time_limit: 150
learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 500000
test_greedy: true
test_interval: 10000
test_nepisode: 32
