env: gfootball
env_args:
  map_name: scenario_layer2_decomposition0_subtask8
  num_agents: 1
  representation: simple115
  rewards: scoring, reward_test
  time_limit: 150
learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 2000
test_greedy: true
test_interval: 10000
test_nepisode: 32
