env: gfootball
env_args:
  map_name: scenario_layer2_decomposition0_subtask5
  num_agents: 3
  representation: simple115
  rewards: scoring, reward_layer2_decomposition0_subtask5_iter0_sample0
  time_limit: 150
learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 500000
test_greedy: true
test_interval: 10000
test_nepisode: 32
