env: gfootball
env_args:
  map_name: scenario_iter0_response0_subtask2
  num_agents: 2
  representation: simple115
  time_limit: 150
learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 200
test_greedy: true
test_interval: 10000
test_nepisode: 32
