env: gfootball
env_args:
  map_name: scenario_layer0_decomposition0_subtask0
  num_agents: 2
  representation: simple115
  rewards: scoring, reward_layer0_decomposition0_subtask0_iter0_sample1
  time_limit: 150
learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 1000000
test_greedy: true
test_interval: 10000
test_nepisode: 32
