env: gfootball
env_args:
  map_name: scenario_layer1_decomposition0_subtask3
  num_agents: 1
  representation: simple115
  rewards: scoring, reward_layer1_decomposition0_subtask3_iter3_sample0
  time_limit: 150
learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 500000
test_greedy: true
test_interval: 10000
test_nepisode: 32
