action_selector: soft_policies
agent_output_type: pi_logits
base_ent: 1.0
base_lr: 1.0
batch_size: 10
batch_size_run: 10
boost_ent_coef: 1.0
boost_lr_coef: 1.0
buffer_size: 10
critic_type: ac_critic
decomposition_id: 0
doe_classifier_cfg:
  doe_type: mlp
  load_doe_buffer_path: /home/zihao/zihao/PycharmProjects/GRF_SUBTASK-0423/doe_epymarl-main/results/buffers/gfootball/0430_ia2c
  load_doe_name: doe_ia2c_layer2_decomposition0_subtask6_iter0_sample0_merged.pt
  load_mode: train
  mlp:
    batch_size: 512
    hidden_sizes:
    - 128
    learning_rate: 0.01
    test_fraction: 0.1
  role_ids:
    goal_6:
    - 0
    goal_7:
    - 1
  save_classifier: true
  save_doe_name: cls_layer2_decomposition0_subtask6_iter0_sample0.pt
doe_type: mlp
ent_coef: 1.0
entropy_coef: 0.01
group_id: 6
hidden_dim: 128
iter_id: 0
layer_id: 2
learner: doe_ia2c_learner
lr: 0.0005
mac: doe_mac
mask_before_softmax: true
name: doe_ia2c
obs_agent_id: true
obs_individual_obs: false
obs_last_action: false
q_nstep: 5
runner: parallel
sample_id: 0
save_buffer: true
save_doe_cls: true
standardise_returns: false
standardise_rewards: true
t_max: 500000
target_update_interval_or_tau: 0.01
time_stamp: 0430_ia2c
use_doe: true
use_rnn: true
