action_selector: soft_policies
agent: rnn_ns
agent_output_type: pi_logits
base_ent: 1.0
base_lr: 1.0
batch_size: 10
batch_size_run: 10
boost_ent_coef: 1.0
boost_lr_coef: 1.0
buffer_size: 10
checkpoint_path: /home/zihao/zihao/PycharmProjects/GRF_SUBTASK-tmp_0513_2/doe_epymarl-main/results/gfootball/2025-05-14-10-38-42/decomposition0/group4
critic_type: ac_critic_ns
decomposition_id: 0
doe_classifier_cfg:
  doe_type: mlp
  layer_tmp_dir: /home/zihao/zihao/PycharmProjects/GRF_SUBTASK-tmp_0513_2/doe_epymarl-main/results/gfootball/2025-05-14-10-38-42/decomposition0/group4
  load_doe_name: cls_layer1_decomposition0_subtask4_iter3_sample0_merged.pt
  load_mode: train
  mlp:
    batch_size: 512
    hidden_sizes:
    - 128
    learning_rate: 0.01
    test_fraction: 0.1
  role_ids:
    goal_6:
    - 0
    goal_7:
    - 1
  save_classifier: true
  save_doe_name: cls_layer1_decomposition0_subtask4_iter3_sample0.pt
doe_type: mlp
ent_coef: 1.0
entropy_coef: 0.01
epochs: 4
eps_clip: 0.2
group_id: 4
iter_id: 3
layer_id: 1
learner: doe_ippo_learner
lr: 0.0003
mac: non_shared_doe_mac
mask_before_softmax: true
name: doe_ippo_ns
obs_agent_id: true
obs_individual_obs: false
obs_last_action: false
q_nstep: 5
runner: parallel
sample_id: 0
save_buffer: true
save_doe_cls: true
standardise_returns: false
standardise_rewards: true
t_max: 500000
target_update_interval_or_tau: 0.01
time_stamp: 2025-05-14-10-38-42
use_doe: true
use_rnn: true
