action_selector: soft_policies
agent_output_type: pi_logits
base_ent: 1.0
base_lr: 1.0
batch_size: 10
batch_size_run: 10
boost_ent_coef: 1.0
boost_lr_coef: 1.0
buffer_size: 10
critic_type: ac_critic
decomposition_id: 0
doe_classifier_cfg:
  doe_type: mlp
  load_doe_buffer_path: /home/zihao/zihao/PycharmProjects/GRF_SUBTASK-0423/doe_epymarl-main/results/buffers/gfootball/0427
  load_doe_name: doe_mappo_layertarget_decomposition0_subtasktarget_itertarget_sampletarget_merged.pt
  load_mode: train
  mlp:
    batch_size: 512
    hidden_sizes:
    - 128
    learning_rate: 0.01
    test_fraction: 0.1
  role_ids:
    goal_0:
    - 0
    - 1
    - 2
    goal_1:
    - 3
    - 4
  save_classifier: true
  save_doe_name: cls_layertarget_decomposition0_subtasktarget_itertarget_sampletarget.pt
doe_type: mlp
ent_coef: 1.0
entropy_coef: 0.01
epochs: 4
eps_clip: 0.2
group_id: target
hidden_dim: 128
iter_id: target
layer_id: target
learner: doe_ppo_learner
lr: 0.0003
mac: doe_mac
mask_before_softmax: true
name: doe_mappo
obs_agent_id: true
obs_individual_obs: false
obs_last_action: false
q_nstep: 5
runner: parallel
sample_id: target
save_buffer: true
save_doe_cls: true
standardise_returns: false
standardise_rewards: true
t_max: 20000000
target_update_interval_or_tau: 0.01
time_stamp: '0427'
use_doe: true
use_rnn: true
