action_selector: soft_policies
agent_output_type: pi_logits
batch_size: 10
batch_size_run: 10
buffer_size: 10
critic_type: ac_critic
decomposition_id: 0
doe_classifier_cfg:
  doe_type: mlp
  load_doe_buffer_path: GRF_SUBTASK/doe_epymarl-main/results/buffer/grf
  load_doe_name: load_mlp_classifier.pt
  load_mode: train
  mlp:
    batch_size: 512
    hidden_sizes:
    - 128
    learning_rate: 1e-2
    test_fraction: 0.1
  role_ids:
    task:
    - 0
    - 1
    - 2
  save_classifier: true
  save_doe_name: save_mlp_classifier.pt
entropy_coef: 0.001
group_id: 1
hidden_dim: 128
iter_id: 0
layer_id: 0
learner: actor_critic_learner
lr: 0.0005
mask_before_softmax: true
name: ia2c
obs_agent_id: true
obs_individual_obs: false
obs_last_action: false
q_nstep: 5
runner: parallel
sample_id: 0
save_buffer: true
save_doe_cls: true
standardise_returns: false
standardise_rewards: true
t_max: 1000000
target_update_interval_or_tau: 0.01
time_stamp: 2024-11-20-15-20-30
use_doe: false
use_rnn: true
