action_selector: soft_policies
agent: rnn_ns
agent_output_type: pi_logits
batch_size: 10
batch_size_run: 1
buffer_size: 10
critic_type: ac_critic_ns
decomposition_id: 0
doe_classifier_cfg:
  doe_type: mlp
  layer_tmp_dir: /home/zihao/zihao/PycharmProjects/GRF_SUBTASK-tmp_0513/doe_epymarl-main/results/gfootball/0513_ia2c_ns_2/decomposition0/group6
  load_doe_buffer_path: GRF_SUBTASK/doe_epymarl-main/results/buffer/grf
  load_doe_name: load_mlp_classifier.pt
  load_mode: train
  mlp:
    batch_size: 512
    hidden_sizes:
    - 128
    learning_rate: 0.01
    test_fraction: 0.1
  role_ids:
    goal_6:
    - 0
    - 1
  save_classifier: true
  save_doe_name: cls_layer2_decomposition0_subtask6_iter0_sample0.pt
entropy_coef: 0.001
group_id: 6
hidden_dim: 128
iter_id: 0
layer_id: 2
learner: actor_critic_learner
lr: 0.0005
mac: non_shared_mac
mask_before_softmax: true
name: ia2c_ns
obs_agent_id: false
obs_individual_obs: false
obs_last_action: false
q_nstep: 5
runner: parallel
sample_id: 0
save_buffer: true
save_doe_cls: true
standardise_returns: false
standardise_rewards: true
t_max: 2000
target_update_interval_or_tau: 200
time_stamp: 0513_ia2c_ns_2
use_doe: false
use_rnn: false
