# --- IA2C NS specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0005

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

mac: "non_shared_mac"
agent: "rnn_ns"
agent_output_type: "pi_logits"
learner: "actor_critic_learner"
entropy_coef: 0.001
standardise_returns: False
standardise_rewards: True
use_rnn: False
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "ac_critic_ns"
name: "ia2c_ns"

t_max: 20050000

use_doe: false
save_buffer: true
save_doe_cls: true


# 新添加doe参数
doe_classifier_cfg:
  doe_type: mlp
  layer_tmp_dir: /data/qiaodan/projects/GRF_SUBTASK/doe_epymarl-main/results/gfootball/0510_ia2c_ns/decomposition0/group6
  load_doe_buffer_path: GRF_SUBTASK/doe_epymarl-main/results/buffer/grf  # 添加这行
  load_doe_name: load_mlp_classifier.pt  # 添加这行
  load_mode: train