




decomposition_id: 0
doe_classifier_cfg:
  doe_type: mlp
  layer_tmp_dir: /home/zihao/zihao/PycharmProjects/GRF_SUBTASK_5v5/doe_epymarl-main/results/gfootball/5v5_1/decomposition0/group7
  load_doe_buffer_path: GRF_SUBTASK/doe_epymarl-main/results/buffer/grf
  load_doe_name: load_mlp_classifier.pt
  load_mode: train
  mlp:
    batch_size: 512
    hidden_sizes:
    - 128
    learning_rate: 0.01
    test_fraction: 0.1
  role_ids:
    goal_7:
    - 0
  save_classifier: true
  save_doe_name: cls_layer2_decomposition0_subtask7_iter3_sample0.pt



group_id: 7
iter_id: 3
layer_id: 2
sample_id: 0

time_stamp: 5v5_1


