[{0: [{'father_group_number': None,
       'group_number': 1,
       'layer': 0,
       'number_of_agents': 3,
       'training_goal': 'Learn the coordinated strategies for offense'},
      {'father_group_number': None,
       'group_number': 2,
       'layer': 0,
       'number_of_agents': 2,
       'training_goal': 'Learn the coordinated strategies for defense'}]},
 {1: [{'father_group_number': 1,
       'group_number': 3,
       'layer': 1,
       'number_of_agents': 1,
       'training_goal': 'learn the offensive actions, which include Shot, Sliding'},
      {'father_group_number': 1,
       'group_number': 4,
       'layer': 1,
       'number_of_agents': 2,
       'training_goal': 'learn the offensive actions, which include Dribble, Pass, and Long Pass'},
      {'father_group_number': 2,
       'group_number': 5,
       'layer': 1,
       'number_of_agents': 1,
       'training_goal': 'learn the defensive actions, which include '
                        'Stop-Dribble, Sprint'},
      {'father_group_number': 2,
       'group_number': 6,
       'layer': 1,
       'number_of_agents': 1,
       'training_goal': 'learn the defensive actions, which include Stop-Moving, Stop-Sprint, and '
                        'Side-Kick.'}
      ]}]
